### ISSUE TITLE
Error Report When running RAiSD

### ISSUE THREAD

**Issue by rosehuang24** [alachins/raisd#18]
Hello!
I have just learned about RAiSD, and I think it is a great algorithm to use in my project. Yet when I test-run I got a error report :

RAiSD: sources/RAiSD_PatternPool.c:770: RSDPatternPool_pushSNP: Assertion `RSDPatternPool->incomingSite[j]=='0' || RSDPatternPool->incomingSite[j]=='1'' failed.
/home/jointforce/default/spool/ibnode161/job_scripts/196649: line 18: 25319 Aborted                 

(core dumped) ~/biosoft/raisd/raisd-master/RAiSD -n test_autobiAexc -I auto_biA_snp.vcf

I really appreciate your help!

Rose

**Comment by alachins** [comment]
It seems that your vcf file contains a character that RAiSD does not recognize. 
I can look into that if you sent me a small sample of your data that reproduces this behavior.
Nikos

**Comment by rosehuang24** [comment]
Hi Nikos

I extracted first 1000 lines of my vcf. Here is the link:
https://github.com/rosehuang24/RAiSD/blob/master/portion.vcf

Thank you very much!
Rose

**Comment by alachins** [comment]
Hi Rose,
Just checked your data and found out that RAiSD fails because of entries like the following, where the GT field (very first one before the first ":") contains a single character:
1:4,4:8:99:1|1:14066_G_C:138,0:14066
Other positions for the same sample comprise two characters. Was this supposed to be 1/1 for example, or should this be interpreted differently?
Nikos

**Comment by rosehuang24** [comment]
Hi Nikos,

I went back and checked and it seems to be the problem. I will re-evaluate my whole pipeline to see where it went wrong. Thank you again so much for your time and help! I will close this discussion for now unless the issue shows up again. 

Thank you
Rose
