### ISSUE TITLE
The shorter the scaffold is, the bigger the mu-statistic value is.

### ISSUE THREAD

**Issue by jiyongkun** [alachins/raisd#5]
The genome has assembled in scaffold level and has more than two thousand scaffolds. But when I did a Manhattan plotting of the result of RAiSD, I found the shorter the scaffold is, the bigger the mu-statistic value is. That is, the regions on shorter scaffold always tend to have bigger mu-statistic value. Thus I cannot compare the mu-statistic value among different scaffolds.
Please see the following image for details. The scaffolds are sorted by length.
<img src="https://i.imgur.com/C2P11vM.jpg" alt="Commercial Photography"></a>

**Comment by alachins** [comment]
Hello and sorry for the late response,
You are right, the values among different scaffolds can not be compared due to the denominator of the muVAR. We designed the mu-statistic so that the values within the same scaffold can be compared. An option to generate scores that can be compared among different scaffolds will be introduced in one of the upcoming releases.

**Comment by alachins** [comment]
RAiSD is now modified (version 2.0 or later) in a way that generates comparable scores among regions of different lengths and sample sizes.
